// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH2Sh6uP1NF_t0weYgEyJ1UN6YUj5wycI',
    appId: '1:571836091673:android:d50da4d12b29c92944c988',
    messagingSenderId: '571836091673',
    projectId: 'depi-test-29f61',
    databaseURL: 'https://depi-test-29f61-default-rtdb.firebaseio.com',
    storageBucket: 'depi-test-29f61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD73RhJ5X2nJEAzXY20eSq1nSPiT9YTe3c',
    appId: '1:571836091673:ios:94290d527cf7a30244c988',
    messagingSenderId: '571836091673',
    projectId: 'depi-test-29f61',
    databaseURL: 'https://depi-test-29f61-default-rtdb.firebaseio.com',
    storageBucket: 'depi-test-29f61.firebasestorage.app',
    iosBundleId: 'com.elgendy.firebaseTest',
  );
}
